version: "3.8"

services:
  app:
    build: .
    ports:
      - "7070:7070"
    environment:
      - PORT=7070
      - WEATHER_API_KEY=9af1063ab3724f35b41215345250904
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=weatherdb
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
